# Generated by Django 4.2.3 on 2023-07-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.TextField(blank=True, null=True)),
                ('summer', models.TextField(blank=True, null=True)),
                ('autumn', models.TextField(blank=True, null=True)),
                ('spring', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('PG', 'Pending'), ('AD', 'Accepted'), ('RD', 'Rejected')], default='New', max_length=150)),
                ('beauty_title', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('other_titles', models.CharField(blank=True, max_length=250, null=True)),
                ('connect', models.CharField(blank=True, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass.coord')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('data', models.URLField()),
                ('passes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pass.pass')),
            ],
        ),
    ]
